# Generated by Django 3.1.3 on 2020-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201122_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventilator_number', models.CharField(max_length=50)),
                ('alloted', models.BooleanField()),
            ],
        ),
    ]
