# Generated by Django 3.1.3 on 2020-11-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ventilator'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allot_ventilator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='ventilator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ventilator'),
        ),
    ]
